# Generated by Django 3.0 on 2020-11-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_s_num', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=100)),
                ('project_abstract', models.TextField()),
                ('project_type', models.CharField(choices=[('Academic', 'Academic'), ('Work', 'Work'), ('Personal', 'Personal')], max_length=30)),
                ('project_organization', models.CharField(max_length=300)),
                ('project_nature', models.CharField(choices=[('Individual', 'Individual'), ('Team', 'Team')], max_length=30)),
                ('project_from', models.DateField()),
                ('project_to', models.DateField()),
                ('project_downloadable', models.BooleanField(default=False)),
                ('project_record_created', models.DateTimeField(auto_now=True)),
                ('project_record_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Projects__project',
            },
        ),
    ]
