# Generated by Django 3.0 on 2020-11-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merits',
            fields=[
                ('merit_s_num', models.AutoField(primary_key=True, serialize=False)),
                ('merit_type', models.CharField(choices=[('Academic', 'Academic'), ('Sports', 'Sports'), ('Professional', 'Professional')], max_length=30)),
                ('merit_title', models.CharField(max_length=200)),
                ('merit_year', models.DateField()),
                ('merit_rank', models.IntegerField()),
                ('merit_description', models.TextField()),
                ('merit_organization', models.CharField(max_length=300)),
                ('merit_downloadable', models.BooleanField(default=False)),
                ('merit_record_created', models.DateTimeField(auto_now=True)),
                ('merit_record_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Achievements__merits',
            },
        ),
    ]
