# Generated by Django 3.0 on 2020-11-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='edu_institute_website',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='school',
            name='edu_institute_website',
            field=models.CharField(default='N/A', max_length=1000),
        ),
    ]
