# Generated by Django 3.0 on 2020-11-29 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('visit_s_num', models.AutoField(primary_key=True, serialize=False)),
                ('visit_destination', models.TextField()),
                ('visit_year', models.DateTimeField()),
                ('visit_description', models.TextField()),
                ('visit_record_created', models.DateTimeField(auto_now=True)),
                ('visit_record_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Footsteps__visits',
            },
        ),
        migrations.CreateModel(
            name='VisitPics',
            fields=[
                ('visit_pic_s_num', models.AutoField(primary_key=True, serialize=False)),
                ('visit_pic_img', models.ImageField(upload_to='static/images/footsteps')),
                ('visit_pic_img_created', models.DateTimeField(auto_now=True)),
                ('visit_s_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footprints.Visits')),
            ],
            options={
                'db_table': 'Footsteps__visit_pics',
            },
        ),
    ]
