# Generated by Django 3.0 on 2020-11-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExp',
            fields=[
                ('workexp_s_num', models.AutoField(primary_key=True, serialize=False)),
                ('workexp_type', models.CharField(choices=[('Internship', 'Intenships'), ('Full-Time', 'Full-Time Professional'), ('Social Service', 'Social Service')], max_length=30)),
                ('workexp_organization', models.CharField(max_length=500)),
                ('workexp_location', models.TextField(max_length=100)),
                ('workexp_industry', models.TextField(max_length=300)),
                ('workexp_from', models.DateField()),
                ('workexp_to', models.DateField()),
                ('workexp_downloadable', models.BooleanField(default=False)),
                ('workexp_record_created', models.DateTimeField(auto_now=True)),
                ('workexp_record_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Work_Experience__work_exp',
            },
        ),
    ]
