# Generated by Django 3.0 on 2020-11-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexp',
            name='workexp_to',
            field=models.DateField(null=True),
        ),
    ]
